# ==========================================================
# =                   ZBOSSBAR CONFIGURATION                   =
# ==========================================================
# 
# Версия Minecraft: 1.21.4
# Автор: Zoobastik
# Версия плагина: 1.0
#
# ФОРМАТИРОВАНИЕ ТЕКСТА:
# ---------------------
# Плагин поддерживает несколько форматов для цветов и оформления текста:
#
# 1. Стандартные цветовые коды: &4, &c, §d и т.д.
#    &0 = Черный         &8 = Темно-серый
#    &1 = Темно-синий    &9 = Синий
#    &2 = Темно-зеленый  &a = Зеленый
#    &3 = Темно-аква     &b = Голубой
#    &4 = Темно-красный  &c = Красный
#    &5 = Фиолетовый     &d = Розовый
#    &6 = Золотой        &e = Желтый
#    &7 = Серый          &f = Белый
#
#    Форматирование: &l (жирный), &o (курсив), &n (подчеркнутый),
#    &m (зачеркнутый), &k (мерцающий), &r (сброс)
#
# 2. HEX-цвета (формат &#RRGGBB):
#    &#FF0000 = Красный, &#00FF00 = Зеленый, &#0000FF = Синий
#
# 3. Градиенты:
#    <gradient:#FF0000:#00FF00>Текст с градиентом</gradient>
#
# ИСПОЛЬЗОВАНИЕ ПЛЕЙСХОЛДЕРОВ:
# ---------------------------
# Вы можете использовать плейсхолдеры PlaceholderAPI в любом тексте.
# Примеры: %player_name%, %server_tps%, %player_health%, %server_online%
#
# При установленном плагине OneBlock будут доступны плейсхолдеры:
# %aoneblock_island_phase%, %aoneblock_island_blocks_to_next_phase% и т.д.

# ==========================================================
# =                  ОСНОВНЫЕ НАСТРОЙКИ                    =
# ==========================================================

# Включить или отключить плагин глобально
# Если установлено false, боссбары не будут показываться никому
enabled: true

# Интервал обновления боссбаров в тиках (20 тиков = 1 секунда)
# Этот параметр влияет на частоту обновления прогресса и 
# плейсхолдеров в тексте боссбаров
update-interval: 20

# Максимальное расстояние, на котором боссбар виден (в блоках)
# Установите -1 для безлимитного расстояния
max-view-distance: -1

# ==========================================================
# =                 НАСТРОЙКИ СОХРАНЕНИЯ                   =
# ==========================================================

# Сохранять состояние боссбара для игроков между перезаходами
# true - состояние (вкл/выкл) боссбара сохраняется для каждого игрока
# false - после перезахода игрока боссбар всегда включен (по умолчанию)
save-player-preferences: true

# Интервал автосохранения данных игроков (в минутах)
# Это влияет на то, как часто данные сохраняются в userdata.yml
auto-save-interval: 5

# ==========================================================
# =              НАСТРОЙКИ ИНТЕГРАЦИИ                      =
# ==========================================================

# Использовать PlaceholderAPI плейсхолдеры в тексте
# Требуется установленный плагин PlaceholderAPI
use-placeholders: true

# Кэширование плейсхолдеров (для улучшения производительности)
# Включите, если на сервере много игроков или используются 
# тяжелые плейсхолдеры
cache-placeholders: false

# Время кэширования плейсхолдеров (в секундах)
# Актуально только если cache-placeholders: true
placeholder-cache-time: 3

# ==========================================================
# =               НАСТРОЙКИ ПЕРЕХОДОВ                      =
# ==========================================================

# Включить плавные переходы между мирами
# true - боссбар плавно меняется при смене мира
# false - боссбар исчезает и появляется заново при смене мира
smooth-world-transitions: true

# Задержка появления боссбара после входа игрока (в тиках)
# Установите выше, если есть проблемы с появлением боссбара
join-delay: 10

# Задержка смены боссбара при смене мира (в тиках)
world-change-delay: 5

# Тип поведения для миров, отсутствующих в конфигурации
# NONE - не показывать боссбар
# DEFAULT - использовать настройки мира "world"
# CREATE - автоматически создать новую секцию для мира
missing-world-behavior: "DEFAULT"

# ==========================================================
# =                НАСТРОЙКИ БОСС-БАРОВ                    =
# ==========================================================
# Настройки для каждого мира определяются отдельно.
# Вы можете создать уникальный боссбар для любого мира.
# 
# Структура настроек для мира:
# 
# worlds:
#   название_мира:
#     enabled: true/false - Включить/выключить боссбар для этого мира
#     
#     # НАСТРОЙКИ ТЕКСТА:
#     title: "Одиночный текст" - Если нужен только один текст
#     titles: - Список текстов для циклического отображения
#       - "Текст 1"
#       - "Текст 2"
#     title-change-interval: 100 - Интервал смены текстов (в тиках)
#     
#     # НАСТРОЙКИ ЦВЕТА И СТИЛЯ:
#     # Доступные цвета: PINK, BLUE, RED, GREEN, YELLOW, PURPLE, WHITE
#     color: "WHITE" - Если нужен только один цвет
#     colors: - Список цветов для анимации
#       - "RED"
#       - "BLUE"
#     
#     # Доступные стили: SOLID, SEGMENTED_6, SEGMENTED_10, SEGMENTED_12, SEGMENTED_20
#     style: "SOLID" - Если нужен только один стиль
#     styles: - Список стилей для анимации
#       - "SOLID"
#       - "SEGMENTED_6"
#     
#     # НАСТРОЙКИ АНИМАЦИИ:
#     animation:
#       enabled: true/false - Включить/выключить анимацию
#       interval: 20 - Интервал смены цветов/стилей (в тиках)
#       reverse: false - Менять цвета/стили в обратном порядке
#       ping-pong: false - Анимация туда-обратно (не циклическая)
#     
#     # НАСТРОЙКИ ПРОГРЕССА:
#     progress:
#       # Типы прогресса:
#       # STATIC - Фиксированное значение
#       # PLAYER_HEALTH - Здоровье игрока (0-100%)
#       # PLAYER_XP - Опыт игрока (0-100%)
#       # PLAYER_LEVEL - Уровень игрока (используйте max-value)
#       # PLAYER_FOOD - Голод игрока (0-100%)
#       # PLAYER_AIR - Воздух игрока (0-100%)
#       # TPS - Производительность сервера (0-20)
#       # TIME - Время суток
#       # CUSTOM - Пользовательское значение из PlaceholderAPI
#       type: "STATIC"
#       
#       # Значение для типа STATIC (от 0.0 до 1.0)
#       value: 1.0
#       
#       # Максимальное значение для типов PLAYER_LEVEL
#       max-value: 100
#       
#       # Плейсхолдер для типа CUSTOM
#       placeholder: "%some_placeholder_value%"
#       
#       # Настройки времени для типа TIME
#       time:
#         format: "HH:mm:ss" - Формат времени
#         server-time: true - Использовать серверное время
#         
#     # ДОПОЛНИТЕЛЬНЫЕ НАСТРОЙКИ:
#     overlay-previous: false - Накладывать поверх боссбара из предыдущего мира
#     permission: "someworld.bossbar" - Право для отображения (опционально)
#     show-on-join: true - Показывать при входе в мир

worlds:
  # ==== ГЛАВНОЕ ЛОББИ СЕРВЕРА ====
  lobby:
    enabled: true
    # Циклические сообщения с интервалом 5 секунд
    titles:
      - "<gradient:#FF0000:#FFAA00>❂ Добро пожаловать, %player_name%! ❂</gradient>"
      - "&eНа сервере играет: &b%server_online% &eигроков"
      - "&a• Используйте &6/bossbar &aдля скрытия этого сообщения"
      - "&d• Приятной игры на нашем сервере! &d❤"
      - "<gradient:#00BBFF:#0044FF>Текущий TPS: %server_tps%</gradient>"
    title-change-interval: 100
    # Цвет и стиль с анимацией
    colors:
      - "BLUE"
      - "GREEN"
      - "PINK"
    style: "SOLID"
    animation:
      enabled: true
      interval: 60
      reverse: false
      ping-pong: true
    progress:
      type: "TIME"
      time:
        format: "HH:mm:ss"
        server-time: true

  # ==== МИР ONEBLOCK ====
  oneblock_world:
    enabled: true
    title: "<gradient:#9933FF:#FF33CC>❂ OneBlock ❂</gradient> &eФаза: &b%aoneblock_visited_island_phase% &7(&6%aoneblock_visited_island_count%&7/&6%aoneblock_visited_island_blocks_to_next_phase%&7)"
    color: "PURPLE"
    style: "SEGMENTED_10"
    animation:
      enabled: false
    progress:
      # Показываем прогресс до следующей фазы
      type: "CUSTOM"
      placeholder: "%aoneblock_visited_island_count_percent%" # Должен возвращать число от 0 до 100
      max-value: 100

  # ==== МИР ВЫЖИВАНИЯ ====
  survival:
    enabled: true
    titles:
      - "<gradient:#33AA33:#AAFF33>❂ Выживание ❂</gradient> &fКоординаты: &a%player_x%&f, &a%player_y%&f, &a%player_z%"
      - "<gradient:#33AA33:#AAFF33>❂ Выживание ❂</gradient> &fЗдоровье: &c%player_health%&f/&c%player_health_max%"
      - "<gradient:#33AA33:#AAFF33>❂ Выживание ❂</gradient> &fВремя: &e%server_time_24%"
    title-change-interval: 80
    color: "GREEN"
    style: "SEGMENTED_6"
    progress:
      type: "PLAYER_HEALTH"

  # ==== НИЖНИЙ МИР ====
  nether:
    enabled: true
    title: "<gradient:#FF3300:#AA0000>❂ Нижний мир ❂</gradient> &cБудьте осторожны! &fОпасная зона!"
    colors:
      - "RED"
      - "YELLOW"
    styles:
      - "SEGMENTED_6"
      - "SEGMENTED_10"
    animation:
      enabled: true
      interval: 40
    progress:
      type: "PLAYER_HEALTH"

  # ==== КРАЙ ====
  the_end:
    enabled: true
    titles:
      - "<gradient:#9900CC:#330066>❂ Край ❂</gradient> &5Энергия: &d%player_health%&5/&d%player_health_max%"
      - "<gradient:#9900CC:#330066>❂ Край ❂</gradient> &5Осторожно! &dВокруг летают эндермены..."
      - "<gradient:#9900CC:#330066>❂ Край ❂</gradient> &5Координаты: &d%player_x%&5, &d%player_y%&5, &d%player_z%"
    title-change-interval: 80
    color: "PURPLE"
    style: "SOLID"
    animation:
      enabled: false
    progress:
      type: "PLAYER_HEALTH"

  # ==== ПРИМЕРЫ ДОПОЛНИТЕЛЬНЫХ МИРОВ ====
  # Скай-блок мир
  skyblock:
    enabled: true
    title: "<gradient:#33CCFF:#3366FF>❂ Небесный остров ❂</gradient> &bУровень острова: &f%askyblock_level%"
    color: "BLUE"
    style: "SOLID"
    progress:
      type: "CUSTOM"
      placeholder: "%askyblock_island_rating%" # Должен возвращать число
      max-value: 1000

  # PvP арена
  pvp_arena:
    enabled: true
    title: "<gradient:#FF0000:#FF6600>⚔ PvP Арена ⚔</gradient> &cУбийства: &f%statistic_player_kills% &7| &cСмерти: &f%statistic_deaths%"
    colors:
      - "RED"
      - "YELLOW"
    style: "SEGMENTED_20"
    animation:
      enabled: true
      interval: 30
      reverse: true
    progress:
      type: "PLAYER_HEALTH"
    permission: "zbossbar.pvpworld" # Только для игроков с этим правом

# ==========================================================
# =                  НАСТРОЙКИ СООБЩЕНИЙ                   =
# ==========================================================
# Здесь вы можете настроить все сообщения плагина
# Используйте & для цветовых кодов

messages:
  prefix: "&8[&b&lZBossbar&8] "
  plugin-enabled: "&aПлагин включен!"
  plugin-disabled: "&cПлагин отключен!"
  player-toggle-on: "&aБоссбар включен для вас!"
  player-toggle-off: "&cБоссбар отключен для вас!"
  reload-success: "&aКонфигурация успешно перезагружена!"
  reload-error: "&cОшибка при перезагрузке конфигурации! Смотрите консоль."
  no-permission: "&cУ вас нет прав для использования этой команды!"
  config-saved: "&aКонфигурация успешно сохранена!"
  world-not-found: "&cМир не найден в конфигурации!"
  help-header: "&8&m-----&r &b&lZBossbar &f&lПомощь &8&m-----"
  help-command: "&b/%command% &8- &7%description%"
  help-footer: "&8&m---------------------------"

# ==========================================================
# =              ТЕХНИЧЕСКИЕ НАСТРОЙКИ                     =
# ==========================================================
# Эти настройки влияют на производительность и поведение плагина
# Изменяйте только если понимаете, что делаете

# Включить отладочный режим (больше логов в консоли)
debug-mode: false

# Лимит боссбаров на одного игрока
# Если несколько миров используют overlay-previous: true
bossbars-per-player-limit: 3

# Изменить таймауты для операций (в миллисекундах)
timeouts:
  bossbar-creation: 100
  placeholder-resolution: 50
  animation-check: 10 